var annotated_dup =
[
    [ "Capacidade", "class_capacidade.html", "class_capacidade" ],
    [ "Cartao", "class_cartao.html", "class_cartao" ],
    [ "Codigo", "class_codigo.html", "class_codigo" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Dinheiro", "class_dinheiro.html", "class_dinheiro" ],
    [ "Email", "class_email.html", "class_email" ],
    [ "Endereco", "class_endereco.html", "class_endereco" ],
    [ "Gerente", "class_gerente.html", "class_gerente" ],
    [ "GerenteService", "class_gerente_service.html", "class_gerente_service" ],
    [ "Hospede", "class_hospede.html", "class_hospede" ],
    [ "HospedeService", "class_hospede_service.html", "class_hospede_service" ],
    [ "Hotel", "class_hotel.html", null ],
    [ "HotelService", "class_hotel_service.html", "class_hotel_service" ],
    [ "IGerenteService", "class_i_gerente_service.html", "class_i_gerente_service" ],
    [ "IHospedeService", "class_i_hospede_service.html", "class_i_hospede_service" ],
    [ "IHotelService", "class_i_hotel_service.html", null ],
    [ "IQuartoService", "class_i_quarto_service.html", "class_i_quarto_service" ],
    [ "IReservaService", "class_i_reserva_service.html", "class_i_reserva_service" ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "Numero", "class_numero.html", "class_numero" ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "Quarto", "class_quarto.html", "class_quarto" ],
    [ "QuartoService", "class_quarto_service.html", "class_quarto_service" ],
    [ "Ramal", "class_ramal.html", "class_ramal" ],
    [ "Reserva", "class_reserva.html", null ],
    [ "ReservaService", "class_reserva_service.html", "class_reserva_service" ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "Telefone", "class_telefone.html", "class_telefone" ]
];